name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build app
        run: |
          go build -o worker ./worker/main.go
          go build -o starter ./starter/main.go

      - name: Run tests
        run: go test ./...

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: <registry> # Replace with your registry URL
          username: ${{ secrets.DOCKER_USERNAME }} # Set your Docker username as a secret in your repository settings
          password: ${{ secrets.DOCKER_PASSWORD }} # Set your Docker password as a secret in your repository settings

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: myrepo/hello-workflow:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: steebchen/kubectl-setup@v1

      - name: Deploy app
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
