name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build app
        run: |
          go build -o worker ./worker/main.go
          go build -o starter ./starter/main.go

      - name: Run tests
        run: go test ./...

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io # Replace with your registry URL
          username: ${{ secrets.DOCKER_USERNAME }} # Set your Docker username as a secret in your repository settings
          password: ${{ secrets.DOCKER_PASSWORD }} # Set your Docker password as a secret in your repository settings

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/amutex/my-temporal-app:v1


deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <AWS_REGION>

    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update kubectl config
      run: aws eks update-kubeconfig --name my-temporal-app --region us-east-1

    - name: Deploy Kubernetes resources
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml